spring:
  application:
    name: NGS
  config:
    import: optional:file:.env[.properties] # .env import

  # database setting
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

# cors setting
cors:
  allowed-origins: https://localhost:3000, http://localhost:3000
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
    - HEAD
  allowed-headers: '*'
  allow-credentials: true
  max-age: 3600

# SpringBoot port
server:
  port: 8080

portone:
  api-secret: ${API_SECRET}